from dataclasses import dataclass, field
from typing import Any, List, Optional

@dataclass
class AIRequestContext:
    """
    A safe, localized representation of the user's context that can be securely
    passed to the LLM. It intentionally omits database IDs (like employee ID, user ID,
    phone numbers) to prevent accidental data leaks or unauthorized cross-referencing.
    """
    employee_name: Optional[str] = None
    language: str = "English"
    person_type: str = "Guest"  # "Employee", "Guest", "Former Employee"
    staff_category: str = ""    # "permanent", "project_contract", "project_deliverable"
    allowed_intents: List[str] = field(default_factory=list)

    @classmethod
    def from_erp_context(cls, erp_context: dict[str, Any]) -> "AIRequestContext":
        """
        Builds the safe AIRequestContext from the raw ERP context dictionary 
        generated by `resolver.get_user_context`.
        """
        return cls(
            employee_name=erp_context.get("full_name"),
            language=erp_context.get("preferred_language", "English"),
            person_type=erp_context.get("person_type", "Guest"),
            staff_category=erp_context.get("staff_category", ""),
            allowed_intents=erp_context.get("allowed_services", []),
        )

    def to_llm_dict(self) -> dict[str, Any]:
        """
        Returns a dictionary suitable for injection into LLM prompts.
        """
        return {
            "name": self.employee_name or "Guest",
            "language": self.language,
            "role": self.person_type,
            "employment_type": self.staff_category,
            "allowed_actions": self.allowed_intents,
        }
