from __future__ import annotations
from typing import Dict, Any, List, Optional

INTENT_CATALOG: Dict[str, Dict[str, Any]] = {
    "leave_balance": {
        "category": "leave",
        "intents": ["leave_balance", "show_leave_balance", "my_leaves", "how_many_leaves"],
        "aliases": ["how many leaves do i have", "what is my leave balance", "show my remaining leaves", "how much leave is left", "mere kitne leaves hain", "meri leave balance batao"],
        "tool": "get_leave_balance",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "create_leave_application": {
        "category": "leave",
        "intents": ["create_leave_application", "apply_leave", "submit_leave"],
        "aliases": ["i want to apply for leave", "submit a leave request for monday", "chutti chahiye", "apply leave"],
        "tool": "create_leave_application",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": False,
        "requires_confirmation": True,
        "llm_allowed": True,
        "response_mode": "interactive",
        "source_type": "ERP"
    },
    "latest_salary_slip": {
        "category": "payroll",
        "intents": ["latest_salary_slip", "salary_slip", "show_salary_slip"],
        "aliases": ["show my salary slip", "salary slip", "show my payslip", "send salary slip", "latest salary", "meri salary slip bhejo"],
        "tool": "get_latest_salary_slip",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "tax_deductions": {
        "category": "payroll",
        "intents": ["tax_deductions", "how_much_tax"],
        "aliases": ["how much was deducted in tax", "my tax deductions", "mera tax kitna kata"],
        "tool": "get_tax_details",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "maternity_leave_policy": {
        "category": "policy",
        "intents": ["maternity_leave_policy"],
        "aliases": ["what is the maternity leave policy", "maternity leave details"],
        "tool": "search_knowledge",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": True,
        "response_mode": "hybrid",
        "source_type": "RAG"
    },
    "leave_application_procedure": {
        "category": "procedure",
        "intents": ["leave_application_procedure", "how_to_apply_leave"],
        "aliases": ["how do i apply for leave", "what is the procedure for leave application"],
        "tool": "search_knowledge",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": True,
        "response_mode": "hybrid",
        "source_type": "FAQ"
    },
    "policy_count": {
        "category": "policy",
        "intents": ["policy_count", "how_many_policies"],
        "aliases": ["how many polices are there", "total policies"],
        "tool": "get_published_policies",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "policy_list": {
        "category": "policy",
        "intents": ["policy_list", "show_policies"],
        "aliases": ["show me the published policies", "list of policies"],
        "tool": "get_published_policies",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "office_timings": {
        "category": "organization",
        "intents": ["office_timings"],
        "aliases": ["what are the office timings", "office hours", "timings"],
        "tool": "get_office_timings",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ORGANIZATION"
    },
    "tax_policy": {
        "category": "policy",
        "intents": ["tax_policy", "why_tax_deducted"],
        "aliases": ["why is tax deducted", "tax rules"],
        "tool": "search_knowledge",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": True,
        "response_mode": "hybrid",
        "source_type": "RAG"
    },
    "carry_forward_leave": {
        "category": "leave",
        "intents": ["carry_forward_leave"],
        "aliases": ["can i carry forward my remaining 4 leaves", "how many leaves can i carry forward"],
        "tool": "leave_read",  # Consolidated read operation
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": True,
        "response_mode": "hybrid",
        "source_type": "MIXED"
    },
    "travel_allowance_policy": {
        "category": "travel",
        "intents": ["travel_allowance_policy"],
        "aliases": ["what is the travel allowance", "travel policy"],
        "tool": "search_knowledge",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": True,
        "response_mode": "hybrid",
        "source_type": "RAG"
    },
    "show_leave": {
        "category": "leave",
        "intents": ["show_leave"],
        "aliases": ["show my leave", "my leave details", "leave record"],
        "tool": "clarification",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "clarification",
        "source_type": "NAVIGATION"
    },
    "today_attendance": {
        "category": "attendance",
        "intents": ["today_attendance", "attendance_summary"],
        "aliases": ["today attendance", "my attendance today", "aaj ki attendance"],
        "tool": "get_attendance_summary",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "profile_gaps": {
        "category": "employee",
        "intents": ["profile_gaps"],
        "aliases": ["my profile gaps", "profile completion"],
        "tool": "get_profile_gaps",
        "requires_employee": True,
        "requires_authentication": True,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "ERP"
    },
    "menu_help": {
        "category": "navigation",
        "intents": ["menu_help", "bot_capabilities"],
        "aliases": ["what can you do", "help", "menu"],
        "tool": "get_menu_help",
        "requires_employee": False,
        "requires_authentication": False,
        "read_only": True,
        "requires_confirmation": False,
        "llm_allowed": False,
        "response_mode": "deterministic",
        "source_type": "NAVIGATION"
    }
}
